# Generated by Django 3.1.7 on 2021-03-11 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='key',
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(default='Location', max_length=64),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
